

services:
   postgresdb:
    container_name: postgresdb
    image: postgres:latest
    restart: always
    ports:
     - "5432" 
    volumes:
     - postgres-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
     - telegrambottest-network
volumes:
  postgres-db-data: