name: deploy
on:
  workflow_dispatch:  
    inputs:
        branch:
           description: 'Branch'     
           required: true
           default: 'develop'  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     
      - name: Build the Docker image
        run: docker build . --file src/TelegramBotTest/Dockerfile --tag telegrambottest
      - name: save
        run: docker  save -o ./telegramBotTest.tar telegrambottest 
      - name: change permission
        run: chmod 777 telegramBotTest.tar
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: telegramBotTest.tar
          target: /home/telegramBotTest/images
     
      - name: deploy app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/telegramBotTest/images
            docker load -i telegramBotTest.tar
            cd ..
            ./stop
            ./start 
