name: deploy
on:
  workflow_dispatch:  
    inputs:
        branch:
           description: 'Branch'     
           required: true
           default: 'develop'  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     
      - name: Build the Docker image
        run: docker build . --file src/TelegramBotTest/Dockerfile --tag telegrambottest
      - name: save
        run: docker  save -o ./telegramBotTest.tar telegramtottest    
      - name: rsync image
        run: touch ~/.rsync.passwd |
             echo password > ~/.rsync.passwd |
             chmod 0600 ~/.rsync.passwd |
             rsync -var --password-file=~/.rsync.passwd admin@servername::/var/www/u2776593/data/telegramBotTest ./telegramBotTest.tar
      - name: deploy app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
